name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++
      uses: actions/setup-cpp@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib

    - name: Configure CMake
      run: cmake .

    - name: Build the project
      run: make

    - name: Run tests
      run: make test
      continue-on-error: true
      

    - name: Collect test results
      if: failure()
      run: exit 1
